import Head from 'next/head'
import Image from 'next/image'
import Brands from '../components/Brands'
import Footer from '../components/Footer'

import Hero from '../components/Hero'
import ImageSlider from '../components/ImageSlider'
import MovieBox from '../components/MovieBox'
import MoviesSection from '../components/MoviesSection'
import { SliderData } from '../components/SliderData'
import styles from '../styles/Home.module.css'
import requests from '../utils/requests.js'

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Disney+ Hotstar - Watch TV Shows & Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Hero /> */}
      <ImageSlider slides={SliderData} />

      <Brands />

      <MoviesSection results={results} />
      <Footer />
    </div>
  )
}

export async function getServerSideProps(context) {
  const fetchTRENDING = await fetch(
    `https://api.themoviedb.org/3${requests.fetchTrending.url} `,
  ).then((res) => res.json())

  const fetchHORROR = await fetch(
    `https://api.themoviedb.org/3${requests.fetchHorrorMovies.url} `,
  ).then((res) => res.json())

  const fetchTopRated = await fetch(
    `https://api.themoviedb.org/3${requests.fetchTopRated.url} `,
  ).then((res) => res.json())
  return {
    props: {
      results: {
        fetchTRENDING,
        fetchHORROR,
        fetchTopRated,
      },
    },
  }
}
